### PR TITLE
Add support to icons based on class

### PR DESCRIPTION
**Pull request by pedroscaff**
Hi @roosta, first of all thanks for the project, I have been using it since I started using i3 three weeks ago hehe. I wanted to play around with how to customize things, and I added this functionality to enable icons alongside the classes.
It can be statically put in the code or loaded through a `toml` file. I put for now just a minimal set as an example for font awesome (both in `toml` and in the code).
I would love to know if you are interested in adding this functionality and I am happy to discuss it.

Here is a screenshot with how it looks using font awesome.
image

### CODE REVIEW

**Comment by pedroscaff** [comment]
I also just saw #3, and with this PR doing it would be much easier since it is already using CLI args and a `Config` struct :).

**Comment by roosta** [comment]
Wow, this is awesome, thank you for taking an interest!

I did happen upon an issue though, I was unable to use the supplied config file, it accepts it just fine, but doesn't render any icon. This could very well be an issue on my end, not sure. It does render the icons if I simply supply `awesome` instead of config file. Maybe a unicode thing?

**Comment by roosta** [comment]
Also I'm definitely interested in adding this, and will go a long way toward adding class name overrides as well.

**Comment by pedroscaff** [comment]
Good to hear, I maybe will have time to finish some changes tomorrow, I now understood how to read the char directly getting rid of building the unicode escape sequence. Now the config file looks like this:

```toml
[icons]
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
```

The icons aren't rendered properly here in the browser, but you get it hehe.
I was planning to do in the same config data another key value map for the classes, so at the end it would be like this

```toml
[icons]
TelegramDesktop = ""
Firefox = ""
Alacritty = ""
Thunderbird = ""

[classes]
TelegramDesktop = "Telegram"
```

What do you think?

**Comment by pedroscaff** [comment]
and I just checked, this actually also worked for me (with colors!)

```toml
[icons]
Firefox = "😛"
```

image

**Comment by roosta** [comment]
I think that sounds great, and neat thing about the smiley :) Once you're satisfied I'll merge and draft a new release.

**Comment by pedroscaff** [comment]
Hi @roosta, I think it should be good now. I also added support for classes aliases so it would close #3. Updated the readme showing how to use the customization options.

**Comment by roosta** [comment]
This is awesome, thanks so much for your effort. This basically completes the featureset I wanted i3wsr to have. I'll add you as a collaborator in case you want to keep tinkering on i3wsr.

**Comment by roosta** [comment]
I located an issue while fixing some tests. Turns out there's an issue when you're not using the config, just running i3wsr regularly, when opening two programs in one workspace results in a space where the icon should be. So for example when having open `gpick` and `xterm` the resulting string is ` xterm | gpick `, while it should be `xterm|gpick`

**Comment by steinex** [comment]
great stuff! thank you! 🎉

**Pull request merged**
